# Generated by Django 3.2 on 2022-04-15 06:52

from django.db import migrations


def initiate(registry, editor):

    Fur = registry.get_model('dogs', 'Fur')
    Size = registry.get_model('dogs', 'Size')
    Breed = registry.get_model('dogs', 'Breed')
    Dog = registry.get_model('dogs', 'Dog')

    short = Fur(fur_name="Short")
    medium = Fur(fur_name="Medium")
    long = Fur(fur_name="Long")

    sizeSmall = Size(size_name="Small")
    sizeMed = Size(size_name="Medium")
    sizeLarge = Size(size_name="Large")

    shep = Breed(breed_name="germanshepherd")
    akita = Breed(breed_name="akitainu")
    shiba = Breed(breed_name="shibainu")
    spitz = Breed(breed_name="pomeranian")

    short.save()
    medium.save()
    long.save()

    sizeSmall.save()
    sizeMed.save()
    sizeLarge.save()

    shep.save()
    shiba.save()
    akita.save()
    spitz.save()

    urls=[
        'https://images.dog.ceo/breeds/deerhound-scottish/n02092002_15064.jpg',
        'https://www.akc.org/wp-content/uploads/2017/11/Pomeranian-On-White-01.jpg',
        'https://images.dog.ceo/breeds/havanese/00100trPORTRAIT_00100_BURST20191222103956878_COVER.jpg',
        'https://images.dog.ceo/breeds/terrier-border/n02093754_2453.jpg',
        'https://images.dog.ceo/breeds/eskimo/n02109961_12993.jpg',
        'https://images.dog.ceo/breeds/terrier-welsh/lucy.jpg',
        'https://images.dog.ceo/breeds/african/n02116738_8696.jpg',
        'https://images.dog.ceo/breeds/husky/n02110185_15019.jpg',
        'https://images.dog.ceo/breeds/hound-walker/n02089867_277.jpg',
        'https://images.dog.ceo/breeds/bullterrier-staffordshire/n02093256_7454.jpg',
        'https://images.dog.ceo/breeds/papillon/n02086910_7999.jpg',
        'https://images.dog.ceo/breeds/terrier-russell/iguet5.jpeg',
    ]

    for i in range(len(urls)):
        n = Dog(size=sizeSmall, fur=long, breed=spitz,
                photo_URL=urls[i])
        n.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initiate)
    ]
